import asyncio
import hashlib

from fastapi import WebSocketDisconnect
from fastapi.testclient import TestClient

from onprem_runtime.api.app import _receive_ws_commands, app, create_app
from onprem_runtime.api.profiles import RuntimeProfile
from onprem_runtime.core.dataset_sync import DatasetSyncCache, build_dataset_frame
from onprem_runtime.core.events import TrainingEvent


class FakeEngine:
    def __init__(self):
        self.stopped = []
        self.cleanup_calls = []

    def list_jobs(self):
        return []

    def get_job(self, job_id):
        raise KeyError(job_id)

    def stop(self, job_id):
        self.stopped.append(job_id)
        return True

    def cleanup_jobs(self, max_age_seconds):
        self.cleanup_calls.append(max_age_seconds)
        return {
            "removed_jobs": ["job_old"],
            "removed_orphan_workspaces": ["job_orphan"],
            "retention_seconds": max_age_seconds,
        }

    async def subscribe(self, job_id):
        yield TrainingEvent(job_id=job_id, phase="completed", data={"status": "completed"})


class FakeWebSocket:
    def __init__(self, messages):
        self.messages = list(messages)

    async def receive_json(self):
        if not self.messages:
            raise WebSocketDisconnect()
        return self.messages.pop(0)


def test_create_app_registers_runtime_routes():
    app = create_app(FakeEngine())
    paths = {route.path for route in app.routes}

    assert "/api/jobs" in paths
    assert "/api/jobs/{job_id}/stop" in paths
    assert "/api/jobs/{job_id}/snapshot" in paths
    assert "/api/stats" in paths
    assert "/api/jobs/cleanup" in paths
    assert "/ws/jobs/{job_id}" in paths
    assert "/api/datasets" in paths
    assert "/ws/datasets/sync" in paths


def test_module_exposes_default_app_for_uvicorn():
    assert app.title == "Neuralese On-Prem Training Runtime"


def test_snapshot_for_missing_job_returns_404():
    client = TestClient(create_app(FakeEngine()))

    response = client.get("/api/jobs/missing/snapshot")

    assert response.status_code == 404
    assert response.json()["detail"] == "job not found"
    assert response.json()["error"] == {
        "code": "job_not_found",
        "message": "job not found",
        "action": "Check the job id and retry after the job has been created.",
    }


def test_invalid_bundle_upload_returns_actionable_error():
    client = TestClient(create_app(FakeEngine()))

    response = client.post(
        "/api/jobs",
        files={"bundle": ("model.txt", b"not a zip", "text/plain")},
    )

    assert response.status_code == 400
    payload = response.json()
    assert payload["detail"] == "Upload must be a .zip ONNX training bundle"
    assert payload["error"] == {
        "code": "invalid_bundle_type",
        "message": "Upload must be a .zip ONNX training bundle",
        "action": "Select a .zip bundle generated by Neuralese and upload it again.",
    }


def test_auth_token_protects_runtime_http_api_when_configured():
    client = TestClient(
        create_app(FakeEngine(), profile=RuntimeProfile.local_school(auth_token="secret"))
    )

    assert client.get("/api/health").status_code == 200
    missing = client.get("/api/jobs")
    wrong = client.get("/api/jobs", headers={"Authorization": "Bearer wrong"})
    bearer = client.get("/api/jobs", headers={"Authorization": "Bearer secret"})
    custom = client.get("/api/jobs", headers={"X-Neuralese-Token": "secret"})

    assert missing.status_code == 401
    assert missing.json()["detail"] == "missing or invalid auth token"
    assert wrong.status_code == 401
    assert bearer.status_code == 200
    assert custom.status_code == 200


def test_auth_token_protects_dataset_http_api_when_configured():
    client = TestClient(
        create_app(FakeEngine(), profile=RuntimeProfile.local_school(auth_token="secret"))
    )

    missing = client.get("/api/datasets")
    ok = client.get("/api/datasets", headers={"Authorization": "Bearer secret"})

    assert missing.status_code == 401
    assert ok.status_code == 200


def test_websocket_stop_command_calls_engine_stop():
    engine = FakeEngine()
    ws = FakeWebSocket([{"type": "stop"}])

    asyncio.run(_receive_ws_commands(ws, engine, "job_123"))

    assert engine.stopped == ["job_123"]


def test_auth_token_protects_job_websocket_when_configured():
    client = TestClient(
        create_app(FakeEngine(), profile=RuntimeProfile.local_school(auth_token="secret"))
    )

    try:
        with client.websocket_connect("/ws/jobs/job_123"):
            raise AssertionError("websocket should require auth token")
    except WebSocketDisconnect as exc:
        assert exc.code == 1008

    with client.websocket_connect("/ws/jobs/job_123?token=secret") as ws:
        assert ws.receive_json()["phase"] == "completed"


def test_auth_token_protects_dataset_sync_websocket_when_configured():
    client = TestClient(
        create_app(
            FakeEngine(),
            profile=RuntimeProfile.local_school(auth_token="secret"),
            dataset_sync=DatasetSyncCache(),
        )
    )
    payload = b"encoded-input-block"
    payload_hash = _sha(payload)

    try:
        with client.websocket_connect("/ws/datasets/sync"):
            raise AssertionError("dataset sync websocket should require auth token")
    except WebSocketDisconnect as exc:
        assert exc.code == 1008

    with client.websocket_connect("/ws/datasets/sync?token=secret") as ws:
        ws.send_json(
            {
                "user_id": "teacher",
                "dataset_id": "local-1",
                "header": {"rows": 2, "inputs_count": 1, "outputs_count": 0},
                "block_hashes": {"inputs": [[payload_hash]], "outputs": []},
                "hash_algo": "sha256",
            }
        )
        assert ws.receive_json() == {"inputs": {"0": [0]}, "outputs": {}}
        ws.send_bytes(build_dataset_frame("inputs", 0, 0, payload))
        ws.send_bytes(b"__end__")
        summary = ws.receive_json()

    assert summary["status"] == "ok"


def test_cleanup_endpoint_calls_engine_retention_cleanup():
    engine = FakeEngine()
    client = TestClient(create_app(engine))

    response = client.post("/api/jobs/cleanup", params={"max_age_seconds": 3600})

    assert response.status_code == 200
    assert engine.cleanup_calls == [3600.0]
    assert response.json() == {
        "removed_jobs": ["job_old"],
        "removed_orphan_workspaces": ["job_orphan"],
        "retention_seconds": 3600.0,
    }


def test_create_app_serves_dashboard_index():
    client = TestClient(create_app(FakeEngine()))

    response = client.get("/")

    assert response.status_code == 200
    assert "Neuralese Runtime" in response.text


def test_datasets_catalog_returns_public_and_cached_local_fingerprints():
    sync_cache = DatasetSyncCache()
    payload = b"encoded"
    payload_hash = _sha(payload)
    sync_cache.prepare_sync(
        "teacher",
        "local-1",
        {"rows": 1},
        {"inputs": [[payload_hash]], "outputs": []},
        hash_algo="sha256",
    )
    synced = sync_cache.apply_frames(
        "teacher",
        "local-1",
        [build_dataset_frame("inputs", 0, 0, payload)],
    )
    client = TestClient(
        create_app(
            FakeEngine(),
            dataset_sync=sync_cache,
            public_datasets={"mnist": {"name": "MNIST"}, "iris": {"name": "Iris"}},
        )
    )

    response = client.get("/api/datasets")

    assert response.status_code == 200
    assert response.json() == {
        "status": "ok",
        "public": {"mnist": {"name": "MNIST"}, "iris": {"name": "Iris"}},
        "cached_local_fingerprints": [synced.fingerprint],
    }


def test_dataset_sync_websocket_requests_missing_blocks_and_returns_summary():
    sync_cache = DatasetSyncCache()
    client = TestClient(create_app(FakeEngine(), dataset_sync=sync_cache))
    payload = b"encoded-input-block"
    payload_hash = _sha(payload)

    with client.websocket_connect("/ws/datasets/sync") as ws:
        ws.send_json(
            {
                "user_id": "teacher",
                "dataset_id": "local-1",
                "header": {"rows": 2, "inputs_count": 1, "outputs_count": 0},
                "block_hashes": {"inputs": [[payload_hash]], "outputs": []},
                "hash_algo": "sha256",
            }
        )
        assert ws.receive_json() == {"inputs": {"0": [0]}, "outputs": {}}
        ws.send_bytes(build_dataset_frame("inputs", 0, 0, payload))
        ws.send_bytes(b"__end__")
        summary = ws.receive_json()

    assert summary["status"] == "ok"
    assert summary["dataset_id"] == "local-1"
    assert summary["rows"] == 2
    assert summary["fingerprint"].startswith("sha256:")
    assert summary["cached_local_fingerprints"] == [summary["fingerprint"]]


def test_dataset_sync_websocket_reuses_cached_blocks():
    sync_cache = DatasetSyncCache()
    client = TestClient(create_app(FakeEngine(), dataset_sync=sync_cache))
    payload = b"same-block"
    payload_hash = _sha(payload)
    metadata = {
        "user_id": "teacher",
        "dataset_id": "local-1",
        "header": {"rows": 1, "inputs_count": 1, "outputs_count": 0},
        "block_hashes": {"inputs": [[payload_hash]], "outputs": []},
        "hash_algo": "sha256",
    }

    with client.websocket_connect("/ws/datasets/sync") as ws:
        ws.send_json(metadata)
        assert ws.receive_json() == {"inputs": {"0": [0]}, "outputs": {}}
        ws.send_bytes(build_dataset_frame("inputs", 0, 0, payload))
        ws.send_bytes(b"__end__")
        first_summary = ws.receive_json()

    with client.websocket_connect("/ws/datasets/sync") as ws:
        ws.send_json(metadata)
        assert ws.receive_json() == {"inputs": {"0": []}, "outputs": {}}
        ws.send_bytes(b"__end__")
        second_summary = ws.receive_json()

    assert second_summary["status"] == "ok"
    assert second_summary["fingerprint"] == first_summary["fingerprint"]


def test_dataset_sync_websocket_returns_error_for_hash_mismatch():
    client = TestClient(create_app(FakeEngine(), dataset_sync=DatasetSyncCache()))

    with client.websocket_connect("/ws/datasets/sync") as ws:
        ws.send_json(
            {
                "user_id": "teacher",
                "dataset_id": "local-1",
                "header": {"rows": 1},
                "block_hashes": {"inputs": [["bad-hash"]], "outputs": []},
                "hash_algo": "sha256",
            }
        )
        assert ws.receive_json() == {"inputs": {"0": [0]}, "outputs": {}}
        ws.send_bytes(build_dataset_frame("inputs", 0, 0, b"payload"))
        ws.send_bytes(b"__end__")
        error = ws.receive_json()

    assert error["status"] == "error"
    assert "hash mismatch" in error["error"]


def _sha(payload: bytes) -> str:
    return hashlib.sha256(payload).hexdigest()
